# Generated by Django 4.1.4 on 2023-05-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=20)),
            ],
        ),
    ]
