# Generated by Django 4.1.4 on 2023-05-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenbed.bedcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
