# Generated by Django 4.1.4 on 2023-05-04 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenbed', '0002_alter_bed_unique_together_alter_bed_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bed',
            name='idx',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='bed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('user', 'location', 'idx')},
        ),
    ]
